use crate::cache::Cache;
use crate::project::Project;
use chrono::Local;
use std::collections::HashMap;
use std::fs::File;
use std::io::Write;
use std::path::Path;

/// A single deletion action in the script
#[derive(Debug, Clone)]
struct ScriptAction {
    /// Path to delete
    path: String,
    /// Size in bytes
    size: u64,
    /// Description for comment
    description: String,
    /// Command to use (rm -rf or special)
    command: String,
    /// Alternative command (official tool) - optional
    alt_command: Option<String>,
    /// Category for grouping
    category: String,
}

/// Script generator for creating reviewable cleanup scripts
pub struct ScriptGenerator {
    actions: Vec<ScriptAction>,
}

impl ScriptGenerator {
    /// Create a new script generator
    pub fn new() -> Self {
        Self {
            actions: Vec::new(),
        }
    }

    /// Add actions from projects
    pub fn add_projects(&mut self, projects: &[Project]) {
        for project in projects {
            for artifact in &project.artifacts {
                self.actions.push(ScriptAction {
                    path: artifact.path.display().to_string(),
                    size: artifact.size,
                    description: format!(
                        "{} - {} ({})",
                        project.name,
                        artifact.name,
                        project.project_type.label()
                    ),
                    command: "rm -rf".to_string(),
                    alt_command: None,
                    category: format!("Build Artifacts ({})", project.project_type.label()),
                });
            }
        }
    }

    /// Add actions from caches
    pub fn add_caches(&mut self, caches: &[Cache]) {
        for cache in caches {
            let alt_command = cache
                .cache_type
                .cleanup_command()
                .map(|(cmd, _)| cmd.to_string());

            self.actions.push(ScriptAction {
                path: cache.path.display().to_string(),
                size: cache.size,
                description: cache.cache_type.description().to_string(),
                command: if cache.cache_type.cleanup_command().is_some() {
                    // For special caches, comment out rm -rf and show the special command
                    "rm -rf".to_string()
                } else {
                    "rm -rf".to_string()
                },
                alt_command,
                category: format!("{} Caches", cache.cache_type.category().label()),
            });
        }
    }

    /// Get total size
    pub fn total_size(&self) -> u64 {
        self.actions.iter().map(|a| a.size).sum()
    }

    /// Get number of actions
    pub fn action_count(&self) -> usize {
        self.actions.len()
    }

    /// Generate the bash script content
    pub fn generate(&self) -> String {
        let mut script = String::new();
        let total_size = self.total_size();

        // Header
        script.push_str("#!/bin/bash\n");
        script.push_str("#\n");
        script.push_str(&format!(
            "# Generated by build-cleaner on {}\n",
            Local::now().format("%Y-%m-%d %H:%M:%S")
        ));
        script.push_str(&format!(
            "# Total space to reclaim: {}\n",
            bytesize::ByteSize(total_size)
        ));
        script.push_str("#\n");
        script.push_str("# REVIEW AND EDIT THIS SCRIPT BEFORE RUNNING!\n");
        script.push_str("# Comment out any lines you want to keep.\n");
        script.push_str("#\n");
        script.push_str("# Usage:\n");
        script.push_str("#   chmod +x cleanup.sh\n");
        script.push_str("#   ./cleanup.sh\n");
        script.push_str("#\n\n");

        // Safety settings
        script.push_str("set -euo pipefail\n\n");

        // Confirmation prompt
        script.push_str("echo \"This script will delete the following items:\"\n");
        script.push_str(&format!(
            "echo \"  - {} items\"\n",
            self.actions.len()
        ));
        script.push_str(&format!(
            "echo \"  - {} total\"\n",
            bytesize::ByteSize(total_size)
        ));
        script.push_str("echo \"\"\n");
        script.push_str("read -p \"Are you sure you want to proceed? (y/N) \" -n 1 -r\n");
        script.push_str("echo\n");
        script.push_str("if [[ ! $REPLY =~ ^[Yy]$ ]]; then\n");
        script.push_str("    echo \"Aborted.\"\n");
        script.push_str("    exit 1\n");
        script.push_str("fi\n\n");
        script.push_str("echo \"Starting cleanup...\"\n");
        script.push_str("echo \"\"\n\n");

        // Group actions by category
        let mut grouped: HashMap<String, Vec<&ScriptAction>> = HashMap::new();
        for action in &self.actions {
            grouped
                .entry(action.category.clone())
                .or_default()
                .push(action);
        }

        // Sort categories by total size
        let mut categories: Vec<_> = grouped.keys().cloned().collect();
        categories.sort_by(|a, b| {
            let size_a: u64 = grouped[a].iter().map(|act| act.size).sum();
            let size_b: u64 = grouped[b].iter().map(|act| act.size).sum();
            size_b.cmp(&size_a)
        });

        // Generate deletion commands grouped by category
        for category in &categories {
            let actions = &grouped[category];
            let category_size: u64 = actions.iter().map(|a| a.size).sum();

            script.push_str(&format!(
                "# === {} ({}) ===\n",
                category,
                bytesize::ByteSize(category_size)
            ));

            for action in actions {
                // Main rm -rf command
                script.push_str(&format!(
                    "{} \"{}\"  # {} - {}\n",
                    action.command,
                    action.path,
                    bytesize::ByteSize(action.size),
                    action.description
                ));

                // Alternative command as comment if available
                if let Some(alt_cmd) = &action.alt_command {
                    script.push_str(&format!(
                        "# Alternative: {}  # Official tool\n",
                        alt_cmd
                    ));
                }
            }

            script.push('\n');
        }

        // Footer
        script.push_str("echo \"\"\n");
        script.push_str(&format!(
            "echo \"Cleanup complete! Freed approximately {}.\"\n",
            bytesize::ByteSize(total_size)
        ));

        script
    }

    /// Write the script to a file
    pub fn write_to_file(&self, path: &Path) -> std::io::Result<()> {
        let content = self.generate();
        let mut file = File::create(path)?;
        file.write_all(content.as_bytes())?;

        // Make executable on Unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = file.metadata()?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(path, perms)?;
        }

        Ok(())
    }
}

impl Default for ScriptGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cache::{Cache, CacheType};
    use crate::project::{Project, ProjectType};
    use std::path::PathBuf;

    #[test]
    fn test_script_generation() {
        let mut generator = ScriptGenerator::new();

        // Add a test project
        let mut project = Project::new(
            "test-project".to_string(),
            ProjectType::Node,
            PathBuf::from("/tmp/test"),
        );
        project.add_artifact(crate::project::Artifact::new(
            PathBuf::from("/tmp/test/node_modules"),
            1_000_000,
        ));

        generator.add_projects(&[project]);

        let script = generator.generate();
        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("rm -rf"));
        assert!(script.contains("/tmp/test/node_modules"));
    }

    #[test]
    fn test_cache_with_alternative_command() {
        let mut generator = ScriptGenerator::new();

        let cache = Cache::new(
            CacheType::Npm,
            PathBuf::from("/home/user/.npm"),
            500_000_000,
        );

        generator.add_caches(&[cache]);

        let script = generator.generate();
        assert!(script.contains("npm cache clean --force"));
    }
}
